services:
  dev:
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: ./development/Dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ~/.ssh
      target: /root/.ssh
    - type: bind
      source: ~/.gitconfig
      target: /root/.gitconfig
