site_name: 'Firewatch Documentation'

nav:
  - Home: README.md
  - 'CLI Usage Guide': cli_usage_guide.md
  - 'Configuration Guide': configuration_guide.md
  - 'Contribution Guide': contribution_guide.md

plugins:
  - techdocs-core
