JIRA_CONFIG_PATH:
DEFAULT_JIRA_PROJECT:
DEFAULT_JIRA_ADDITIONAL_LABELS:
RULES_CONFIG_FILE_PATH:
FAIL_WITH_TEST_FAILURES:
FAIL_WITH_POD_FAILURES:
TEMP_FOR_ENV:
KEEP_JOB_DIR:
ADDITIONAL_LABELS_FILE:
VERBOSE_TEST_FAILURE_REPORTING:
VERBOSE_TEST_FAILURE_REPORTING_TICKET_LIMIT:
#gcs_bucket: str,
#gcs_creds_file: Optional[str],
