name: pr-verification

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Run Tox
        run: uv run --with tox-uv tox
